// integrations/supabase/client.ts
// This file is automatically generated. Do not edit it directly.

import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { logger } from "@/lib/logger";

// Variables de entorno (Vite expone solo vars con prefijo VITE_):
//   VITE_SUPABASE_URL         → URL del proyecto Supabase
//   VITE_SUPABASE_ANON_KEY    → clave pública anónima (o publishable key)
//
// Fallbacks: también acepta NEXT_PUBLIC_ para compatibilidad multi-entorno.

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ??
  import.meta.env.VITE_NEXT_PUBLIC_SUPABASE_URL

const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.VITE_NEXT_PUBLIC_SUPABASE_ANON_KEY

const isDev = import.meta.env.DEV

// Storage seguro (browser vs Workers/SSR).
const storage =
  typeof window !== 'undefined' && typeof window.localStorage !== 'undefined'
    ? window.localStorage
    : undefined

if ((!SUPABASE_URL || !SUPABASE_ANON_KEY) && isDev) {
  logger.warn(
    '[supabase] Configuración incompleta: asegúrate de definir ' +
    'VITE_SUPABASE_URL y VITE_SUPABASE_ANON_KEY en .env.development.local.',
  )
}

// Declaración global para singleton (Vite HMR safe).
declare global {
  var __supabase__: SupabaseClient<Database> | undefined
}

function createSupabaseClient(): SupabaseClient<Database> {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    throw new Error(
      '[supabase] Configuración incompleta: define VITE_SUPABASE_URL y VITE_SUPABASE_ANON_KEY ' +
      'en .env.local o .env. Copia .env.example como .env y completa los valores.',
    )
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  })
}

// Singleton protegido con globalThis.
export const supabase: SupabaseClient<Database> =
  globalThis.__supabase__ ?? createSupabaseClient()

globalThis.__supabase__ = supabase

// Importa el cliente así desde el resto del proyecto:
//
//   import { supabase } from '@/integrations/supabase/client'
//
// Cualquier error de configuración se manifestará al inicializar el módulo,
// no en puntos aleatorios de la ejecución.
